export const AVAILABLE_ACTIVE_ICONS = [
  'left-arrow',
  'right-arrow',
  'account',
  'hamburger',
  'trash',
  'trash-fill',
  'stopwatch',
  'stopwatch-fill',
  'heart',
  'heart-fill',
  'plus',
  'funnel',
  'funnel-fill',
  'pencil',
  'pencil-fill',
  'x',
  'x-lg',
  'arrow-bar-left',
  'arrow-bar-right',
  'tag',
  'tag-fill',
  'tags',
  'tags-fill',
  'code',
  'box',
  'enter-right',
] as const;

export type AvailableReactiveIcon = (typeof AVAILABLE_ACTIVE_ICONS)[number];
