services:
  recipe_book_frontend:
    image: ghcr.io/jeffrey-carr/recipe_book-frontend:latest
    container_name: recipe_book_frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - '127.0.0.1:3002:3000'

  recipe_book_backend:
    image: ghcr.io/jeffrey-carr/recipe_book-backend:latest
    container_name: recipe_book_backend
    restart: unless-stopped
    volumes:
      - ./backend/docker.env:/app/.env:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '127.0.0.1:3102:8080'
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    ports:
      - '127.0.0.1:6379:6379'
    restart: unless-stopped
