# Deployment workflow for web_games
name: Deploy Web Games
on:
  push:
    tags:
      - 'web_games-v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
