import { v4 as uuid } from 'uuid';

export { resizeObserver } from './page';
export * from './browser';
export * from './date';
export * from './network';

export const ping = (): string => {
  return "pong!";
};

export const sleep = (ms: number): Promise<void> => {
  return new Promise(resolve => setTimeout(resolve, ms));
};

// place files you want to import through the `$lib` alias in this folder.
export const generateRandomNumber = (min: number, max?: number): number => {
  if (max == null) {
    max = min;
    min = 0;
  }

  return Math.random() * max + min;
};

// generateRandomInt generates a random whole number between min (inclusive)
// and max (exclusive)
export const generateRandomInt = (min: number, max?: number): number => {
  return Math.floor(generateRandomNumber(min, max));
};

export const getRandomElement = <T>(arr: T[]): T => {
  const index = generateRandomInt(arr.length);
  return arr[index];
};

export const getRandomHexColor = (): string => {
  return `#${Math.floor(Math.random() * 0xffffff).toString(16).padStart(6, '0')}`;
};

export const generateGreeting = (): string => {
  return getRandomElement([
    "Hello",
    "Hi",
    "Hey",
    "Yo",
    "Sup",
    "Howdy",
    "Ahoy",
    "Greetings",
    "Welcome",
    "Hola",
    "Aloha",
    "Salutations",
    "Hiya",
    "G'day",
    "Heya",
    "Heyo",
    "Yello",
  ]);
};

// generateUUID generates a new uuid. This should mostly be used for rendering, and any
// important UUIDs should be generated by the BE
export const generateUUID = (): string => {
  return uuid();
};
